from django import forms

class NominationForm(forms.Form):
    post_title = forms.CharField(max_length=100)
    gender = forms.CharField(max_length=100)
    TITLE_CHOICES = ('Mr', 'Mrs', 'Ms', 'Prof', 'Dr')
    title = forms.CharField(max_length=3,
    widget = forms.Select(choices=TITLE_CHOICES),)
    first_name = forms.CharField(max_length=100)
    surname = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=254)
    phone_number = forms.CharField(max_length=20)
    home_address = forms.CharField(max_length=200)
    dob = forms.DateField(auto_now=False, auto_now_add=False)
    discipline = forms.CharField(max_length=1000)
    new_or_replacement = forms.ChoiceField('New','Replacement')
    additional_remuneration = forms.CharField(max_length=500)
    hours_per_week = forms.SmallIntegerField()
    commencement_date = forms.DateField(auto_now=False, auto_now_add=False)
    school = forms.CharField(max_length=100)
    is_new_work_group = forms.BooleanField()
    work_group_title = forms.CharField(max_length=100)
    work_group_owner = forms.CharField(max_length=100)
    qual_title = forms.CharField(max_length=100)
    qual_awarding_body = forms.CharField(max_length=100)
    nationality = forms.CharField(max_length=100)
    is_permit_required = forms.BooleanField()
    contract_type = forms.ChoiceField('Permanent','Specific Purpose','Fixed Term')
    salary = forms.IntegerField()
    first_increment_date = forms.DateField(auto_now=False, auto_now_add=False)
    increment_amount = forms.SmallIntegerField()
    is_NWA = forms.BooleanField()
    termination_date = forms.DateField(auto_now=False, auto_now_add=False)
    project_title = forms.CharField(max_length=100)
    grant_source = forms.SmallIntegerField()
    principal_investigator = forms.CharField(max_length=100)
    annual_leave = forms.SmallIntegerField()
    additional_comments = forms.CharField(max_length=1000)
